project_id = "vcymocxqfbowuvihtdku"

[functions.health-query]
verify_jwt = false

[functions.admin-queries]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.sms-webhook]
verify_jwt = false
